site_name: mas airgap install

theme:
  name: readthedocs
  language: en
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
  feature:
    - navigation.instant


extra_css:
  - extra.css


nav:
  - "Guides":
      - "Airgap installation":
        - "Overview": 00-airgapsteps.md
        - "Deploy Image Registry":
          - "Deploy the VM and extend disk": 05-vm_extend_disk.md
          - "Deploy image registry in VM": 10-airgap_deployregistry_vm.md
          - "Deploy registry in OCP": 11-airgap_deployregistry_ocp.md
        - "Mirror images to the registry":
          - "mirror mas and dependencies": 20-airgap_mirorimages.md
          - "mirror redhat images": 25-mirror-redhat-images.md
        - "Configure OpenShift for mirror": 35-airgap_configureocpformirror.md
        - "Simulate an airgap environment": 40-airgap_simulateairgap.md
        - "Additional Information":
          - "Containers": 01-airgap_podmancommands.md
  - "Troubleshooting":
    - "Mobile": spatial.md

